name: Deploy to Development Environment

on:
  push:
    branches:
      - dev  # Triggers workflow only when pushing to the dev branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js (if you're using Node for Firebase functions)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase (Dev Environment)
      run: firebase deploy --only hosting:dev
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
