name: Deploy to Firebase Main

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Main
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_MAIN }}  # Use the secret stored in GitHub
        run: firebase deploy --only hosting:main  # Deploy to the production hosting site
