name: Firebase Deploy to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Firebase credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > "$HOME/serviceAccount.json"
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/serviceAccount.json"

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "$HOME/serviceAccount.json"
        run: firebase deploy --only hosting
