name: Deploy to Firebase Dev

on:
  push:
    branches:
      - dev-root  # Trigger on pushes to dev-root branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev  # Specify the GitHub environment where secrets are stored
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Reference the secret as `secrets.FIREBASE_TOKEN`
        run: firebase deploy --only hosting:dev
