name: Deploy to Firebase Hosting on PR Merge

on:
  push:
    branches:
      - root-dev
      - root-test
      - root-main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test, prod]
        branch: [root-dev, root-test, root-main]

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Firebase environment variables
        run: |
          # Set the environment variables based on the branch
          if [[ "${{ matrix.branch }}" == "root-dev" ]]; then
            echo "FIREBASE_SITE=public-dev" >> $GITHUB_ENV
          elif [[ "${{ matrix.branch }}" == "root-test" ]]; then
            echo "FIREBASE_SITE=public-test" >> $GITHUB_ENV
          elif [[ "${{ matrix.branch }}" == "root-main" ]]; then
            echo "FIREBASE_SITE=public-prod" >> $GITHUB_ENV
          fi
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Run build.sh script
        run: |
          chmod +x ./build.sh  # Make sure build.sh is executable
          ./build.sh  # Run the build script

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting:${{ env.FIREBASE_SITE }} --project ${{ env.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
