
name: Deploy to Firebase Dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev  # Link to GitHub dev environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: |
          cd WordleWebApp  # Adjust path if necessary
          npm install

      - name: Build React App
        run: |
          cd WordleWebApp  # Adjust path if necessary
          npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_DEV }}
        run: firebase deploy --only hosting:dev --project word-buster-99508
