name: Deploy to Firebase Test

on:
  push:
    branches:
      - test-root  # Trigger the workflow when changes are pushed to test-root

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_TEST }}  # Use the secret stored in GitHub
        run: firebase deploy --only hosting:test  # Deploy to the test hosting site
