
name: Deploy to Firebase Test

on:
  push:
    branches:
      - test-root  # Trigger on pushes to test-root branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test  # Specify the GitHub environment for test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_TEST }}  # Reference the secret for test environment
        run: firebase deploy --only hosting:test
